BEGIN 
    FOR X IN (
        SELECT
            TABLE_NAME
        FROM 
            USER_TABLES
        WHERE
            TABLE_NAME = 'PEDIDO_NOVO' 
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' 
                            ||X.TABLE_NAME
                            ||' CASCADE CONSTRAINTS;
    END LOOP;
END;

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER(20) NOT NULL PRIMARY KEY,
    NOME_CLIENTE VARCHAR2(100),
    DT_NASC DATE,
    EMAIL VARCHAR2(50),
    CPF_CNPJ NUMBER(15),
    ID_TIPO_CLIENTE NUMBER(20),
    ID_GENERO NUMBER(20),
    ID_ENDERECO NUMBER(20)    
);

CREATE TABLE TIPO_CLIENTE (
    ID_TIPO_CLIENTE NUMBER(20) NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR2(200)
);

CREATE TABLE GENERO (
    ID_GENERO NUMBER(20) NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR2(200) NOT NULL
);

CREATE TABLE ENDERECO(
    ID_ENDERECO NUMBER(20) NOT NULL,
    
);